const PRIVATE_ENV = {
  GRPC_URL: process.env.ETCO_GRPC_URL,
  EVE_AUTH_CLIENT_ID: process.env.ETCO_EVE_AUTH_CLIENT_ID,
  EVE_AUTH_CLIENT_SECRET: process.env.ETCO_EVE_AUTH_CLIENT_SECRET,
  EVE_MARKETS_CLIENT_ID: process.env.ETCO_EVE_MARKETS_CLIENT_ID,
  EVE_MARKETS_CLIENT_SECRET: process.env.ETCO_EVE_MARKETS_CLIENT_SECRET,
  EVE_STRUCTURE_INFO_CLIENT_ID: process.env.ETCO_EVE_STRUCTURE_INFO_CLIENT_ID,
  EVE_STRUCTURE_INFO_CLIENT_SECRET: process.env.ETCO_EVE_STRUCTURE_INFO_CLIENT_SECRET,
  EVE_CORPORATION_CLIENT_ID: process.env.ETCO_EVE_CORPORATION_CLIENT_ID,
  EVE_CORPORATION_CLIENT_SECRET: process.env.ETCO_EVE_CORPORATION_CLIENT_SECRET,
};

module.exports = { PRIVATE_ENV };
