// @generated by protobuf-ts 2.9.0
// @generated from protobuf file "etco.proto" (package "eve_trading_co_proto", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { EveTradingCo } from "./etco";
import type { StatusShopAppraisalResponse } from "./etco";
import type { StatusShopAppraisalRequest } from "./etco";
import type { StatusBuybackAppraisalResponse } from "./etco";
import type { StatusBuybackAppraisalRequest } from "./etco";
import type { GetShopAppraisalResponse } from "./etco";
import type { GetShopAppraisalRequest } from "./etco";
import type { GetBuybackAppraisalResponse } from "./etco";
import type { GetBuybackAppraisalRequest } from "./etco";
import type { ShopCancelPurchaseResponse } from "./etco";
import type { ShopCancelPurchaseRequest } from "./etco";
import type { ShopMakePurchaseResponse } from "./etco";
import type { ShopMakePurchaseRequest } from "./etco";
import type { ShopInventoryResponse } from "./etco";
import type { ShopInventoryRequest } from "./etco";
import type { UserDataResponse } from "./etco";
import type { UserDataRequest } from "./etco";
import type { NewShopAppraisalResponse } from "./etco";
import type { NewShopAppraisalRequest } from "./etco";
import type { NewBuybackAppraisalResponse } from "./etco";
import type { NewBuybackAppraisalRequest } from "./etco";
import type { ParseResponse } from "./etco";
import type { ParseRequest } from "./etco";
import type { EsiAppLoginResponse } from "./etco";
import type { EsiAppLoginRequest } from "./etco";
import type { ShopDeletePurchasesResponse } from "./etco";
import type { ShopDeletePurchasesRequest } from "./etco";
import type { CfgMergeMarketsResponse } from "./etco";
import type { CfgMergeMarketsRequest } from "./etco";
import type { CfgMergeShopLocationsResponse } from "./etco";
import type { CfgMergeShopLocationsRequest } from "./etco";
import type { CfgMergeBuybackSystemsResponse } from "./etco";
import type { CfgMergeBuybackSystemsRequest } from "./etco";
import type { CfgMergeShopLocationTypeMapsBuilderResponse } from "./etco";
import type { CfgMergeShopLocationTypeMapsBuilderRequest } from "./etco";
import type { CfgMergeBuybackSystemTypeMapsBuilderResponse } from "./etco";
import type { CfgMergeBuybackSystemTypeMapsBuilderRequest } from "./etco";
import type { CfgSetAuthListResponse } from "./etco";
import type { CfgSetAuthListRequest } from "./etco";
import type { CfgGetMarketsResponse } from "./etco";
import type { CfgGetMarketsRequest } from "./etco";
import type { CfgGetShopLocationsResponse } from "./etco";
import type { CfgGetShopLocationsRequest } from "./etco";
import type { CfgGetBuybackSystemsResponse } from "./etco";
import type { CfgGetBuybackSystemsRequest } from "./etco";
import type { CfgGetShopLocationTypeMapsBuilderResponse } from "./etco";
import type { CfgGetShopLocationTypeMapsBuilderRequest } from "./etco";
import type { CfgGetBuybackSystemTypeMapsBuilderResponse } from "./etco";
import type { CfgGetBuybackSystemTypeMapsBuilderRequest } from "./etco";
import type { CfgGetAuthListResponse } from "./etco";
import type { CfgGetAuthListRequest } from "./etco";
import type { BuybackContractQueueResponse } from "./etco";
import type { BuybackContractQueueRequest } from "./etco";
import type { ShopContractQueueResponse } from "./etco";
import type { ShopContractQueueRequest } from "./etco";
import type { ShopPurchaseQueueResponse } from "./etco";
import type { ShopPurchaseQueueRequest } from "./etco";
import type { BuybackSystemsResponse } from "./etco";
import type { BuybackSystemsRequest } from "./etco";
import type { ShopLocationsResponse } from "./etco";
import type { ShopLocationsRequest } from "./etco";
import type { NamedSDETypeDataResponse } from "./etco";
import type { NamedSDETypeDataRequest } from "./etco";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SDETypeDataResponse } from "./etco";
import type { SDETypeDataRequest } from "./etco";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
// message Shop

// message BuybackContra

/**
 * // STATIC ENDPOINTS // // (nextJS static generation / static JS file)
 *
 * @generated from protobuf service eve_trading_co_proto.EveTradingCo
 */
export interface IEveTradingCoClient {
    /**
     * lists every SDE type that is published and has a market group
     *
     * @generated from protobuf rpc: SDETypeData(eve_trading_co_proto.SDETypeDataRequest) returns (eve_trading_co_proto.SDETypeDataResponse);
     */
    sDETypeData(input: SDETypeDataRequest, options?: RpcOptions): UnaryCall<SDETypeDataRequest, SDETypeDataResponse>;
    /**
     * @generated from protobuf rpc: NamedSDETypeData(eve_trading_co_proto.NamedSDETypeDataRequest) returns (eve_trading_co_proto.NamedSDETypeDataResponse);
     */
    namedSDETypeData(input: NamedSDETypeDataRequest, options?: RpcOptions): UnaryCall<NamedSDETypeDataRequest, NamedSDETypeDataResponse>;
    /**
     * returns a list of all valid shop locations
     *
     * @generated from protobuf rpc: ShopLocations(eve_trading_co_proto.ShopLocationsRequest) returns (eve_trading_co_proto.ShopLocationsResponse);
     */
    shopLocations(input: ShopLocationsRequest, options?: RpcOptions): UnaryCall<ShopLocationsRequest, ShopLocationsResponse>;
    /**
     * returns a list of all valid buyback systems
     *
     * @generated from protobuf rpc: BuybackSystems(eve_trading_co_proto.BuybackSystemsRequest) returns (eve_trading_co_proto.BuybackSystemsResponse);
     */
    buybackSystems(input: BuybackSystemsRequest, options?: RpcOptions): UnaryCall<BuybackSystemsRequest, BuybackSystemsResponse>;
    // // ADMIN ENDPOINTS // //

    /**
     * lists the purchase order queue (purchase orders with no contract)
     *
     * @generated from protobuf rpc: ShopPurchaseQueue(eve_trading_co_proto.ShopPurchaseQueueRequest) returns (eve_trading_co_proto.ShopPurchaseQueueResponse);
     */
    shopPurchaseQueue(input: ShopPurchaseQueueRequest, options?: RpcOptions): UnaryCall<ShopPurchaseQueueRequest, ShopPurchaseQueueResponse>;
    /**
     * lists active contracts, and, optionally, their original appraisals, new prices, and location info
     *
     * purchase queue + contract
     *
     * @generated from protobuf rpc: ShopContractQueue(eve_trading_co_proto.ShopContractQueueRequest) returns (eve_trading_co_proto.ShopContractQueueResponse);
     */
    shopContractQueue(input: ShopContractQueueRequest, options?: RpcOptions): UnaryCall<ShopContractQueueRequest, ShopContractQueueResponse>;
    /**
     * contracts
     *
     * @generated from protobuf rpc: BuybackContractQueue(eve_trading_co_proto.BuybackContractQueueRequest) returns (eve_trading_co_proto.BuybackContractQueueResponse);
     */
    buybackContractQueue(input: BuybackContractQueueRequest, options?: RpcOptions): UnaryCall<BuybackContractQueueRequest, BuybackContractQueueResponse>;
    /**
     * lists the request config data
     *
     * @generated from protobuf rpc: CfgGetAuthList(eve_trading_co_proto.CfgGetAuthListRequest) returns (eve_trading_co_proto.CfgGetAuthListResponse);
     */
    cfgGetAuthList(input: CfgGetAuthListRequest, options?: RpcOptions): UnaryCall<CfgGetAuthListRequest, CfgGetAuthListResponse>;
    /**
     * @generated from protobuf rpc: CfgGetBuybackSystemTypeMapsBuilder(eve_trading_co_proto.CfgGetBuybackSystemTypeMapsBuilderRequest) returns (eve_trading_co_proto.CfgGetBuybackSystemTypeMapsBuilderResponse);
     */
    cfgGetBuybackSystemTypeMapsBuilder(input: CfgGetBuybackSystemTypeMapsBuilderRequest, options?: RpcOptions): UnaryCall<CfgGetBuybackSystemTypeMapsBuilderRequest, CfgGetBuybackSystemTypeMapsBuilderResponse>;
    /**
     * @generated from protobuf rpc: CfgGetShopLocationTypeMapsBuilder(eve_trading_co_proto.CfgGetShopLocationTypeMapsBuilderRequest) returns (eve_trading_co_proto.CfgGetShopLocationTypeMapsBuilderResponse);
     */
    cfgGetShopLocationTypeMapsBuilder(input: CfgGetShopLocationTypeMapsBuilderRequest, options?: RpcOptions): UnaryCall<CfgGetShopLocationTypeMapsBuilderRequest, CfgGetShopLocationTypeMapsBuilderResponse>;
    /**
     * @generated from protobuf rpc: CfgGetBuybackSystems(eve_trading_co_proto.CfgGetBuybackSystemsRequest) returns (eve_trading_co_proto.CfgGetBuybackSystemsResponse);
     */
    cfgGetBuybackSystems(input: CfgGetBuybackSystemsRequest, options?: RpcOptions): UnaryCall<CfgGetBuybackSystemsRequest, CfgGetBuybackSystemsResponse>;
    /**
     * @generated from protobuf rpc: CfgGetShopLocations(eve_trading_co_proto.CfgGetShopLocationsRequest) returns (eve_trading_co_proto.CfgGetShopLocationsResponse);
     */
    cfgGetShopLocations(input: CfgGetShopLocationsRequest, options?: RpcOptions): UnaryCall<CfgGetShopLocationsRequest, CfgGetShopLocationsResponse>;
    /**
     * @generated from protobuf rpc: CfgGetMarkets(eve_trading_co_proto.CfgGetMarketsRequest) returns (eve_trading_co_proto.CfgGetMarketsResponse);
     */
    cfgGetMarkets(input: CfgGetMarketsRequest, options?: RpcOptions): UnaryCall<CfgGetMarketsRequest, CfgGetMarketsResponse>;
    /**
     * replaces the existing config data with the given config data
     *
     * @generated from protobuf rpc: CfgSetAuthList(eve_trading_co_proto.CfgSetAuthListRequest) returns (eve_trading_co_proto.CfgSetAuthListResponse);
     */
    cfgSetAuthList(input: CfgSetAuthListRequest, options?: RpcOptions): UnaryCall<CfgSetAuthListRequest, CfgSetAuthListResponse>;
    /**
     * merges the given config data into the existing config data
     *
     * @generated from protobuf rpc: CfgMergeBuybackSystemTypeMapsBuilder(eve_trading_co_proto.CfgMergeBuybackSystemTypeMapsBuilderRequest) returns (eve_trading_co_proto.CfgMergeBuybackSystemTypeMapsBuilderResponse);
     */
    cfgMergeBuybackSystemTypeMapsBuilder(input: CfgMergeBuybackSystemTypeMapsBuilderRequest, options?: RpcOptions): UnaryCall<CfgMergeBuybackSystemTypeMapsBuilderRequest, CfgMergeBuybackSystemTypeMapsBuilderResponse>;
    /**
     * @generated from protobuf rpc: CfgMergeShopLocationTypeMapsBuilder(eve_trading_co_proto.CfgMergeShopLocationTypeMapsBuilderRequest) returns (eve_trading_co_proto.CfgMergeShopLocationTypeMapsBuilderResponse);
     */
    cfgMergeShopLocationTypeMapsBuilder(input: CfgMergeShopLocationTypeMapsBuilderRequest, options?: RpcOptions): UnaryCall<CfgMergeShopLocationTypeMapsBuilderRequest, CfgMergeShopLocationTypeMapsBuilderResponse>;
    /**
     * @generated from protobuf rpc: CfgMergeBuybackSystems(eve_trading_co_proto.CfgMergeBuybackSystemsRequest) returns (eve_trading_co_proto.CfgMergeBuybackSystemsResponse);
     */
    cfgMergeBuybackSystems(input: CfgMergeBuybackSystemsRequest, options?: RpcOptions): UnaryCall<CfgMergeBuybackSystemsRequest, CfgMergeBuybackSystemsResponse>;
    /**
     * @generated from protobuf rpc: CfgMergeShopLocations(eve_trading_co_proto.CfgMergeShopLocationsRequest) returns (eve_trading_co_proto.CfgMergeShopLocationsResponse);
     */
    cfgMergeShopLocations(input: CfgMergeShopLocationsRequest, options?: RpcOptions): UnaryCall<CfgMergeShopLocationsRequest, CfgMergeShopLocationsResponse>;
    /**
     * @generated from protobuf rpc: CfgMergeMarkets(eve_trading_co_proto.CfgMergeMarketsRequest) returns (eve_trading_co_proto.CfgMergeMarketsResponse);
     */
    cfgMergeMarkets(input: CfgMergeMarketsRequest, options?: RpcOptions): UnaryCall<CfgMergeMarketsRequest, CfgMergeMarketsResponse>;
    /**
     * cancels the purchase orders for the given codes
     *
     * @generated from protobuf rpc: ShopDeletePurchases(eve_trading_co_proto.ShopDeletePurchasesRequest) returns (eve_trading_co_proto.ShopDeletePurchasesResponse);
     */
    shopDeletePurchases(input: ShopDeletePurchasesRequest, options?: RpcOptions): UnaryCall<ShopDeletePurchasesRequest, ShopDeletePurchasesResponse>;
    /**
     * logs into the requested app
     *
     * @generated from protobuf rpc: EsiAppLogin(eve_trading_co_proto.EsiAppLoginRequest) returns (eve_trading_co_proto.EsiAppLoginResponse);
     */
    esiAppLogin(input: EsiAppLoginRequest, options?: RpcOptions): UnaryCall<EsiAppLoginRequest, EsiAppLoginResponse>;
    // // USER ENDPOINTS // //

    /**
     * parses an input string into a list of named basic items
     *
     * @generated from protobuf rpc: Parse(eve_trading_co_proto.ParseRequest) returns (eve_trading_co_proto.ParseResponse);
     */
    parse(input: ParseRequest, options?: RpcOptions): UnaryCall<ParseRequest, ParseResponse>;
    /**
     * returns a buyback appraisal for the provided items and its code (if saved)
     *
     * @generated from protobuf rpc: NewBuybackAppraisal(eve_trading_co_proto.NewBuybackAppraisalRequest) returns (eve_trading_co_proto.NewBuybackAppraisalResponse);
     */
    newBuybackAppraisal(input: NewBuybackAppraisalRequest, options?: RpcOptions): UnaryCall<NewBuybackAppraisalRequest, NewBuybackAppraisalResponse>;
    /**
     * returns a shop appraisal for the provided items
     *
     * @generated from protobuf rpc: NewShopAppraisal(eve_trading_co_proto.NewShopAppraisalRequest) returns (eve_trading_co_proto.NewShopAppraisalResponse);
     */
    newShopAppraisal(input: NewShopAppraisalRequest, options?: RpcOptions): UnaryCall<NewShopAppraisalRequest, NewShopAppraisalResponse>;
    /**
     * returns the users appraisal codes
     *
     * @generated from protobuf rpc: UserData(eve_trading_co_proto.UserDataRequest) returns (eve_trading_co_proto.UserDataResponse);
     */
    userData(input: UserDataRequest, options?: RpcOptions): UnaryCall<UserDataRequest, UserDataResponse>;
    /**
     * returns purchasable items for the given location
     *
     * @generated from protobuf rpc: ShopInventory(eve_trading_co_proto.ShopInventoryRequest) returns (eve_trading_co_proto.ShopInventoryResponse);
     */
    shopInventory(input: ShopInventoryRequest, options?: RpcOptions): UnaryCall<ShopInventoryRequest, ShopInventoryResponse>;
    /**
     * places a purchase order for the given items and location
     *
     * @generated from protobuf rpc: ShopMakePurchase(eve_trading_co_proto.ShopMakePurchaseRequest) returns (eve_trading_co_proto.ShopMakePurchaseResponse);
     */
    shopMakePurchase(input: ShopMakePurchaseRequest, options?: RpcOptions): UnaryCall<ShopMakePurchaseRequest, ShopMakePurchaseResponse>;
    /**
     * cancel the purchase order for the given code
     *
     * @generated from protobuf rpc: ShopCancelPurchase(eve_trading_co_proto.ShopCancelPurchaseRequest) returns (eve_trading_co_proto.ShopCancelPurchaseResponse);
     */
    shopCancelPurchase(input: ShopCancelPurchaseRequest, options?: RpcOptions): UnaryCall<ShopCancelPurchaseRequest, ShopCancelPurchaseResponse>;
    // // ADMIN / USER ENDPOINTS // // (override via parameters)

    /**
     * returns the appraisal for the given code
     *
     * @generated from protobuf rpc: GetBuybackAppraisal(eve_trading_co_proto.GetBuybackAppraisalRequest) returns (eve_trading_co_proto.GetBuybackAppraisalResponse);
     */
    getBuybackAppraisal(input: GetBuybackAppraisalRequest, options?: RpcOptions): UnaryCall<GetBuybackAppraisalRequest, GetBuybackAppraisalResponse>;
    /**
     * @generated from protobuf rpc: GetShopAppraisal(eve_trading_co_proto.GetShopAppraisalRequest) returns (eve_trading_co_proto.GetShopAppraisalResponse);
     */
    getShopAppraisal(input: GetShopAppraisalRequest, options?: RpcOptions): UnaryCall<GetShopAppraisalRequest, GetShopAppraisalResponse>;
    /**
     * returns the status for the given code
     * only the character that made the appraisal is authenticated (unless admin is true)
     *
     * @generated from protobuf rpc: StatusBuybackAppraisal(eve_trading_co_proto.StatusBuybackAppraisalRequest) returns (eve_trading_co_proto.StatusBuybackAppraisalResponse);
     */
    statusBuybackAppraisal(input: StatusBuybackAppraisalRequest, options?: RpcOptions): UnaryCall<StatusBuybackAppraisalRequest, StatusBuybackAppraisalResponse>;
    /**
     * @generated from protobuf rpc: StatusShopAppraisal(eve_trading_co_proto.StatusShopAppraisalRequest) returns (eve_trading_co_proto.StatusShopAppraisalResponse);
     */
    statusShopAppraisal(input: StatusShopAppraisalRequest, options?: RpcOptions): UnaryCall<StatusShopAppraisalRequest, StatusShopAppraisalResponse>;
}
// message Shop

// message BuybackContra

/**
 * // STATIC ENDPOINTS // // (nextJS static generation / static JS file)
 *
 * @generated from protobuf service eve_trading_co_proto.EveTradingCo
 */
export class EveTradingCoClient implements IEveTradingCoClient, ServiceInfo {
    typeName = EveTradingCo.typeName;
    methods = EveTradingCo.methods;
    options = EveTradingCo.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * lists every SDE type that is published and has a market group
     *
     * @generated from protobuf rpc: SDETypeData(eve_trading_co_proto.SDETypeDataRequest) returns (eve_trading_co_proto.SDETypeDataResponse);
     */
    sDETypeData(input: SDETypeDataRequest, options?: RpcOptions): UnaryCall<SDETypeDataRequest, SDETypeDataResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SDETypeDataRequest, SDETypeDataResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: NamedSDETypeData(eve_trading_co_proto.NamedSDETypeDataRequest) returns (eve_trading_co_proto.NamedSDETypeDataResponse);
     */
    namedSDETypeData(input: NamedSDETypeDataRequest, options?: RpcOptions): UnaryCall<NamedSDETypeDataRequest, NamedSDETypeDataResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<NamedSDETypeDataRequest, NamedSDETypeDataResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * returns a list of all valid shop locations
     *
     * @generated from protobuf rpc: ShopLocations(eve_trading_co_proto.ShopLocationsRequest) returns (eve_trading_co_proto.ShopLocationsResponse);
     */
    shopLocations(input: ShopLocationsRequest, options?: RpcOptions): UnaryCall<ShopLocationsRequest, ShopLocationsResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ShopLocationsRequest, ShopLocationsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * returns a list of all valid buyback systems
     *
     * @generated from protobuf rpc: BuybackSystems(eve_trading_co_proto.BuybackSystemsRequest) returns (eve_trading_co_proto.BuybackSystemsResponse);
     */
    buybackSystems(input: BuybackSystemsRequest, options?: RpcOptions): UnaryCall<BuybackSystemsRequest, BuybackSystemsResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<BuybackSystemsRequest, BuybackSystemsResponse>("unary", this._transport, method, opt, input);
    }
    // // ADMIN ENDPOINTS // //

    /**
     * lists the purchase order queue (purchase orders with no contract)
     *
     * @generated from protobuf rpc: ShopPurchaseQueue(eve_trading_co_proto.ShopPurchaseQueueRequest) returns (eve_trading_co_proto.ShopPurchaseQueueResponse);
     */
    shopPurchaseQueue(input: ShopPurchaseQueueRequest, options?: RpcOptions): UnaryCall<ShopPurchaseQueueRequest, ShopPurchaseQueueResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ShopPurchaseQueueRequest, ShopPurchaseQueueResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * lists active contracts, and, optionally, their original appraisals, new prices, and location info
     *
     * purchase queue + contract
     *
     * @generated from protobuf rpc: ShopContractQueue(eve_trading_co_proto.ShopContractQueueRequest) returns (eve_trading_co_proto.ShopContractQueueResponse);
     */
    shopContractQueue(input: ShopContractQueueRequest, options?: RpcOptions): UnaryCall<ShopContractQueueRequest, ShopContractQueueResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<ShopContractQueueRequest, ShopContractQueueResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * contracts
     *
     * @generated from protobuf rpc: BuybackContractQueue(eve_trading_co_proto.BuybackContractQueueRequest) returns (eve_trading_co_proto.BuybackContractQueueResponse);
     */
    buybackContractQueue(input: BuybackContractQueueRequest, options?: RpcOptions): UnaryCall<BuybackContractQueueRequest, BuybackContractQueueResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<BuybackContractQueueRequest, BuybackContractQueueResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * lists the request config data
     *
     * @generated from protobuf rpc: CfgGetAuthList(eve_trading_co_proto.CfgGetAuthListRequest) returns (eve_trading_co_proto.CfgGetAuthListResponse);
     */
    cfgGetAuthList(input: CfgGetAuthListRequest, options?: RpcOptions): UnaryCall<CfgGetAuthListRequest, CfgGetAuthListResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgGetAuthListRequest, CfgGetAuthListResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgGetBuybackSystemTypeMapsBuilder(eve_trading_co_proto.CfgGetBuybackSystemTypeMapsBuilderRequest) returns (eve_trading_co_proto.CfgGetBuybackSystemTypeMapsBuilderResponse);
     */
    cfgGetBuybackSystemTypeMapsBuilder(input: CfgGetBuybackSystemTypeMapsBuilderRequest, options?: RpcOptions): UnaryCall<CfgGetBuybackSystemTypeMapsBuilderRequest, CfgGetBuybackSystemTypeMapsBuilderResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgGetBuybackSystemTypeMapsBuilderRequest, CfgGetBuybackSystemTypeMapsBuilderResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgGetShopLocationTypeMapsBuilder(eve_trading_co_proto.CfgGetShopLocationTypeMapsBuilderRequest) returns (eve_trading_co_proto.CfgGetShopLocationTypeMapsBuilderResponse);
     */
    cfgGetShopLocationTypeMapsBuilder(input: CfgGetShopLocationTypeMapsBuilderRequest, options?: RpcOptions): UnaryCall<CfgGetShopLocationTypeMapsBuilderRequest, CfgGetShopLocationTypeMapsBuilderResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgGetShopLocationTypeMapsBuilderRequest, CfgGetShopLocationTypeMapsBuilderResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgGetBuybackSystems(eve_trading_co_proto.CfgGetBuybackSystemsRequest) returns (eve_trading_co_proto.CfgGetBuybackSystemsResponse);
     */
    cfgGetBuybackSystems(input: CfgGetBuybackSystemsRequest, options?: RpcOptions): UnaryCall<CfgGetBuybackSystemsRequest, CfgGetBuybackSystemsResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgGetBuybackSystemsRequest, CfgGetBuybackSystemsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgGetShopLocations(eve_trading_co_proto.CfgGetShopLocationsRequest) returns (eve_trading_co_proto.CfgGetShopLocationsResponse);
     */
    cfgGetShopLocations(input: CfgGetShopLocationsRequest, options?: RpcOptions): UnaryCall<CfgGetShopLocationsRequest, CfgGetShopLocationsResponse> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgGetShopLocationsRequest, CfgGetShopLocationsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgGetMarkets(eve_trading_co_proto.CfgGetMarketsRequest) returns (eve_trading_co_proto.CfgGetMarketsResponse);
     */
    cfgGetMarkets(input: CfgGetMarketsRequest, options?: RpcOptions): UnaryCall<CfgGetMarketsRequest, CfgGetMarketsResponse> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgGetMarketsRequest, CfgGetMarketsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * replaces the existing config data with the given config data
     *
     * @generated from protobuf rpc: CfgSetAuthList(eve_trading_co_proto.CfgSetAuthListRequest) returns (eve_trading_co_proto.CfgSetAuthListResponse);
     */
    cfgSetAuthList(input: CfgSetAuthListRequest, options?: RpcOptions): UnaryCall<CfgSetAuthListRequest, CfgSetAuthListResponse> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgSetAuthListRequest, CfgSetAuthListResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * merges the given config data into the existing config data
     *
     * @generated from protobuf rpc: CfgMergeBuybackSystemTypeMapsBuilder(eve_trading_co_proto.CfgMergeBuybackSystemTypeMapsBuilderRequest) returns (eve_trading_co_proto.CfgMergeBuybackSystemTypeMapsBuilderResponse);
     */
    cfgMergeBuybackSystemTypeMapsBuilder(input: CfgMergeBuybackSystemTypeMapsBuilderRequest, options?: RpcOptions): UnaryCall<CfgMergeBuybackSystemTypeMapsBuilderRequest, CfgMergeBuybackSystemTypeMapsBuilderResponse> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgMergeBuybackSystemTypeMapsBuilderRequest, CfgMergeBuybackSystemTypeMapsBuilderResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgMergeShopLocationTypeMapsBuilder(eve_trading_co_proto.CfgMergeShopLocationTypeMapsBuilderRequest) returns (eve_trading_co_proto.CfgMergeShopLocationTypeMapsBuilderResponse);
     */
    cfgMergeShopLocationTypeMapsBuilder(input: CfgMergeShopLocationTypeMapsBuilderRequest, options?: RpcOptions): UnaryCall<CfgMergeShopLocationTypeMapsBuilderRequest, CfgMergeShopLocationTypeMapsBuilderResponse> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgMergeShopLocationTypeMapsBuilderRequest, CfgMergeShopLocationTypeMapsBuilderResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgMergeBuybackSystems(eve_trading_co_proto.CfgMergeBuybackSystemsRequest) returns (eve_trading_co_proto.CfgMergeBuybackSystemsResponse);
     */
    cfgMergeBuybackSystems(input: CfgMergeBuybackSystemsRequest, options?: RpcOptions): UnaryCall<CfgMergeBuybackSystemsRequest, CfgMergeBuybackSystemsResponse> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgMergeBuybackSystemsRequest, CfgMergeBuybackSystemsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgMergeShopLocations(eve_trading_co_proto.CfgMergeShopLocationsRequest) returns (eve_trading_co_proto.CfgMergeShopLocationsResponse);
     */
    cfgMergeShopLocations(input: CfgMergeShopLocationsRequest, options?: RpcOptions): UnaryCall<CfgMergeShopLocationsRequest, CfgMergeShopLocationsResponse> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgMergeShopLocationsRequest, CfgMergeShopLocationsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgMergeMarkets(eve_trading_co_proto.CfgMergeMarketsRequest) returns (eve_trading_co_proto.CfgMergeMarketsResponse);
     */
    cfgMergeMarkets(input: CfgMergeMarketsRequest, options?: RpcOptions): UnaryCall<CfgMergeMarketsRequest, CfgMergeMarketsResponse> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgMergeMarketsRequest, CfgMergeMarketsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * cancels the purchase orders for the given codes
     *
     * @generated from protobuf rpc: ShopDeletePurchases(eve_trading_co_proto.ShopDeletePurchasesRequest) returns (eve_trading_co_proto.ShopDeletePurchasesResponse);
     */
    shopDeletePurchases(input: ShopDeletePurchasesRequest, options?: RpcOptions): UnaryCall<ShopDeletePurchasesRequest, ShopDeletePurchasesResponse> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<ShopDeletePurchasesRequest, ShopDeletePurchasesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * logs into the requested app
     *
     * @generated from protobuf rpc: EsiAppLogin(eve_trading_co_proto.EsiAppLoginRequest) returns (eve_trading_co_proto.EsiAppLoginResponse);
     */
    esiAppLogin(input: EsiAppLoginRequest, options?: RpcOptions): UnaryCall<EsiAppLoginRequest, EsiAppLoginResponse> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<EsiAppLoginRequest, EsiAppLoginResponse>("unary", this._transport, method, opt, input);
    }
    // // USER ENDPOINTS // //

    /**
     * parses an input string into a list of named basic items
     *
     * @generated from protobuf rpc: Parse(eve_trading_co_proto.ParseRequest) returns (eve_trading_co_proto.ParseResponse);
     */
    parse(input: ParseRequest, options?: RpcOptions): UnaryCall<ParseRequest, ParseResponse> {
        const method = this.methods[21], opt = this._transport.mergeOptions(options);
        return stackIntercept<ParseRequest, ParseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * returns a buyback appraisal for the provided items and its code (if saved)
     *
     * @generated from protobuf rpc: NewBuybackAppraisal(eve_trading_co_proto.NewBuybackAppraisalRequest) returns (eve_trading_co_proto.NewBuybackAppraisalResponse);
     */
    newBuybackAppraisal(input: NewBuybackAppraisalRequest, options?: RpcOptions): UnaryCall<NewBuybackAppraisalRequest, NewBuybackAppraisalResponse> {
        const method = this.methods[22], opt = this._transport.mergeOptions(options);
        return stackIntercept<NewBuybackAppraisalRequest, NewBuybackAppraisalResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * returns a shop appraisal for the provided items
     *
     * @generated from protobuf rpc: NewShopAppraisal(eve_trading_co_proto.NewShopAppraisalRequest) returns (eve_trading_co_proto.NewShopAppraisalResponse);
     */
    newShopAppraisal(input: NewShopAppraisalRequest, options?: RpcOptions): UnaryCall<NewShopAppraisalRequest, NewShopAppraisalResponse> {
        const method = this.methods[23], opt = this._transport.mergeOptions(options);
        return stackIntercept<NewShopAppraisalRequest, NewShopAppraisalResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * returns the users appraisal codes
     *
     * @generated from protobuf rpc: UserData(eve_trading_co_proto.UserDataRequest) returns (eve_trading_co_proto.UserDataResponse);
     */
    userData(input: UserDataRequest, options?: RpcOptions): UnaryCall<UserDataRequest, UserDataResponse> {
        const method = this.methods[24], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserDataRequest, UserDataResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * returns purchasable items for the given location
     *
     * @generated from protobuf rpc: ShopInventory(eve_trading_co_proto.ShopInventoryRequest) returns (eve_trading_co_proto.ShopInventoryResponse);
     */
    shopInventory(input: ShopInventoryRequest, options?: RpcOptions): UnaryCall<ShopInventoryRequest, ShopInventoryResponse> {
        const method = this.methods[25], opt = this._transport.mergeOptions(options);
        return stackIntercept<ShopInventoryRequest, ShopInventoryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * places a purchase order for the given items and location
     *
     * @generated from protobuf rpc: ShopMakePurchase(eve_trading_co_proto.ShopMakePurchaseRequest) returns (eve_trading_co_proto.ShopMakePurchaseResponse);
     */
    shopMakePurchase(input: ShopMakePurchaseRequest, options?: RpcOptions): UnaryCall<ShopMakePurchaseRequest, ShopMakePurchaseResponse> {
        const method = this.methods[26], opt = this._transport.mergeOptions(options);
        return stackIntercept<ShopMakePurchaseRequest, ShopMakePurchaseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * cancel the purchase order for the given code
     *
     * @generated from protobuf rpc: ShopCancelPurchase(eve_trading_co_proto.ShopCancelPurchaseRequest) returns (eve_trading_co_proto.ShopCancelPurchaseResponse);
     */
    shopCancelPurchase(input: ShopCancelPurchaseRequest, options?: RpcOptions): UnaryCall<ShopCancelPurchaseRequest, ShopCancelPurchaseResponse> {
        const method = this.methods[27], opt = this._transport.mergeOptions(options);
        return stackIntercept<ShopCancelPurchaseRequest, ShopCancelPurchaseResponse>("unary", this._transport, method, opt, input);
    }
    // // ADMIN / USER ENDPOINTS // // (override via parameters)

    /**
     * returns the appraisal for the given code
     *
     * @generated from protobuf rpc: GetBuybackAppraisal(eve_trading_co_proto.GetBuybackAppraisalRequest) returns (eve_trading_co_proto.GetBuybackAppraisalResponse);
     */
    getBuybackAppraisal(input: GetBuybackAppraisalRequest, options?: RpcOptions): UnaryCall<GetBuybackAppraisalRequest, GetBuybackAppraisalResponse> {
        const method = this.methods[28], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBuybackAppraisalRequest, GetBuybackAppraisalResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetShopAppraisal(eve_trading_co_proto.GetShopAppraisalRequest) returns (eve_trading_co_proto.GetShopAppraisalResponse);
     */
    getShopAppraisal(input: GetShopAppraisalRequest, options?: RpcOptions): UnaryCall<GetShopAppraisalRequest, GetShopAppraisalResponse> {
        const method = this.methods[29], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetShopAppraisalRequest, GetShopAppraisalResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * returns the status for the given code
     * only the character that made the appraisal is authenticated (unless admin is true)
     *
     * @generated from protobuf rpc: StatusBuybackAppraisal(eve_trading_co_proto.StatusBuybackAppraisalRequest) returns (eve_trading_co_proto.StatusBuybackAppraisalResponse);
     */
    statusBuybackAppraisal(input: StatusBuybackAppraisalRequest, options?: RpcOptions): UnaryCall<StatusBuybackAppraisalRequest, StatusBuybackAppraisalResponse> {
        const method = this.methods[30], opt = this._transport.mergeOptions(options);
        return stackIntercept<StatusBuybackAppraisalRequest, StatusBuybackAppraisalResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: StatusShopAppraisal(eve_trading_co_proto.StatusShopAppraisalRequest) returns (eve_trading_co_proto.StatusShopAppraisalResponse);
     */
    statusShopAppraisal(input: StatusShopAppraisalRequest, options?: RpcOptions): UnaryCall<StatusShopAppraisalRequest, StatusShopAppraisalResponse> {
        const method = this.methods[31], opt = this._transport.mergeOptions(options);
        return stackIntercept<StatusShopAppraisalRequest, StatusShopAppraisalResponse>("unary", this._transport, method, opt, input);
    }
}
