// @generated by protobuf-ts 2.9.0 with parameter ts_nocheck,server_none,long_type_number
// @generated from protobuf file "etco.proto" (package "etco_proto", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { EveTradingCo } from "./etco";
import type { CfgMergeMarketsRequest } from "./etco";
import type { CfgMergeShopLocationsRequest } from "./etco";
import type { CfgMergeBuybackSystemsRequest } from "./etco";
import type { CfgMergeShopLocationTypeMapsBuilderRequest } from "./etco";
import type { CfgMergeBuybackSystemTypeMapsBuilderRequest } from "./etco";
import type { CfgSetConstDataRequest } from "./etco";
import type { CfgUpdateResponse } from "./etco";
import type { CfgSetAuthListRequest } from "./etco";
import type { CfgGetConstDataResponse } from "./etco";
import type { CfgGetShopBundleKeysResponse } from "./etco";
import type { CfgGetBuybackBundleKeysResponse } from "./etco";
import type { CfgGetMarketNamesResponse } from "./etco";
import type { CfgGetMarketsResponse } from "./etco";
import type { CfgGetShopLocationsResponse } from "./etco";
import type { CfgGetBuybackSystemsResponse } from "./etco";
import type { CfgGetShopLocationTypeMapsBuilderResponse } from "./etco";
import type { CfgGetBuybackSystemTypeMapsBuilderResponse } from "./etco";
import type { CfgGetAuthListResponse } from "./etco";
import type { GetShopAppraisalResponse } from "./etco";
import type { GetBuybackAppraisalResponse } from "./etco";
import type { GetAppraisalRequest } from "./etco";
import type { StatusAppraisalResponse } from "./etco";
import type { StatusAppraisalRequest } from "./etco";
import type { SaveAppraisalRequest } from "./etco";
import type { ShopInventoryResponse } from "./etco";
import type { ShopInventoryRequest } from "./etco";
import type { UserTimePurchaseResponse } from "./etco";
import type { UserAppraisalCodesResponse } from "./etco";
import type { UserDataRequest } from "./etco";
import type { CancelPurchaseResponse } from "./etco";
import type { CancelPurchaseRequest } from "./etco";
import type { DeletePurchasesResponse } from "./etco";
import type { DeletePurchasesRequest } from "./etco";
import type { LocationPurchaseQueueResponse } from "./etco";
import type { LocationPurchaseQueueRequest } from "./etco";
import type { PurchaseQueueResponse } from "./etco";
import type { ShopContractQueueResponse } from "./etco";
import type { BuybackContractQueueResponse } from "./etco";
import type { BasicRequest } from "./etco";
import type { TokenInfoResponse } from "./etco";
import type { TokenInfoRequest } from "./etco";
import type { ShopAppraisalResponse } from "./etco";
import type { BuybackAppraisalResponse } from "./etco";
import type { NewAppraisalRequest } from "./etco";
import type { AllianceInfoResponse } from "./etco";
import type { CorporationInfoResponse } from "./etco";
import type { CharacterInfoResponse } from "./etco";
import type { EntityInfoRequest } from "./etco";
import type { ParseResponse } from "./etco";
import type { ParseRequest } from "./etco";
import type { LoginResponse } from "./etco";
import type { LoginRequest } from "./etco";
import type { LocationsResponse } from "./etco";
import type { LocationsRequest } from "./etco";
import type { AllShopLocationsResponse } from "./etco";
import type { SystemsRequest } from "./etco";
import type { SystemsResponse } from "./etco";
import type { NamedTypesRequest } from "./etco";
import type { NamedTypesResponse } from "./etco";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { TypesResponse } from "./etco";
import type { EmptyRequest } from "./etco";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * // (Anonymous) (Static)
 *
 * @generated from protobuf service etco_proto.EveTradingCo
 */
export interface IEveTradingCoClient {
    /**
     * every published type with a market group
     *
     * @generated from protobuf rpc: AllTypes(etco_proto.EmptyRequest) returns (etco_proto.TypesResponse);
     */
    allTypes(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, TypesResponse>;
    /**
     * @generated from protobuf rpc: AllNamedTypes(etco_proto.EmptyRequest) returns (etco_proto.NamedTypesResponse);
     */
    allNamedTypes(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, NamedTypesResponse>;
    /**
     * requested published types with a market group
     *
     * @generated from protobuf rpc: NamedTypes(etco_proto.NamedTypesRequest) returns (etco_proto.NamedTypesResponse);
     */
    namedTypes(input: NamedTypesRequest, options?: RpcOptions): UnaryCall<NamedTypesRequest, NamedTypesResponse>;
    /**
     * every available buyback system
     *
     * @generated from protobuf rpc: AllBuybackSystems(etco_proto.EmptyRequest) returns (etco_proto.SystemsResponse);
     */
    allBuybackSystems(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, SystemsResponse>;
    /**
     * every system
     *
     * @generated from protobuf rpc: AllSystems(etco_proto.EmptyRequest) returns (etco_proto.SystemsResponse);
     */
    allSystems(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, SystemsResponse>;
    /**
     * requested systems
     *
     * @generated from protobuf rpc: Systems(etco_proto.SystemsRequest) returns (etco_proto.SystemsResponse);
     */
    systems(input: SystemsRequest, options?: RpcOptions): UnaryCall<SystemsRequest, SystemsResponse>;
    // // (Anonymous)

    /**
     * every available shop location
     *
     * @generated from protobuf rpc: AllShopLocations(etco_proto.EmptyRequest) returns (etco_proto.AllShopLocationsResponse);
     */
    allShopLocations(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, AllShopLocationsResponse>;
    /**
     * requested locations
     *
     * @generated from protobuf rpc: Locations(etco_proto.LocationsRequest) returns (etco_proto.LocationsResponse);
     */
    locations(input: LocationsRequest, options?: RpcOptions): UnaryCall<LocationsRequest, LocationsResponse>;
    /**
     * logs into the requested app (users will only ever use the Auth app)
     *
     * @generated from protobuf rpc: Login(etco_proto.LoginRequest) returns (etco_proto.LoginResponse);
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse>;
    /**
     * parses an input string into a list of named basic items
     *
     * @generated from protobuf rpc: Parse(etco_proto.ParseRequest) returns (etco_proto.ParseResponse);
     */
    parse(input: ParseRequest, options?: RpcOptions): UnaryCall<ParseRequest, ParseResponse>;
    /**
     * retrieves information about the given entity
     *
     * @generated from protobuf rpc: CharacterInfo(etco_proto.EntityInfoRequest) returns (etco_proto.CharacterInfoResponse);
     */
    characterInfo(input: EntityInfoRequest, options?: RpcOptions): UnaryCall<EntityInfoRequest, CharacterInfoResponse>;
    /**
     * @generated from protobuf rpc: CorporationInfo(etco_proto.EntityInfoRequest) returns (etco_proto.CorporationInfoResponse);
     */
    corporationInfo(input: EntityInfoRequest, options?: RpcOptions): UnaryCall<EntityInfoRequest, CorporationInfoResponse>;
    /**
     * @generated from protobuf rpc: AllianceInfo(etco_proto.EntityInfoRequest) returns (etco_proto.AllianceInfoResponse);
     */
    allianceInfo(input: EntityInfoRequest, options?: RpcOptions): UnaryCall<EntityInfoRequest, AllianceInfoResponse>;
    /**
     * creates a new appraisal that is not saved and will not be retrievable later
     *
     * @generated from protobuf rpc: NewBuybackAppraisal(etco_proto.NewAppraisalRequest) returns (etco_proto.BuybackAppraisalResponse);
     */
    newBuybackAppraisal(input: NewAppraisalRequest, options?: RpcOptions): UnaryCall<NewAppraisalRequest, BuybackAppraisalResponse>;
    /**
     * @generated from protobuf rpc: NewShopAppraisal(etco_proto.NewAppraisalRequest) returns (etco_proto.ShopAppraisalResponse);
     */
    newShopAppraisal(input: NewAppraisalRequest, options?: RpcOptions): UnaryCall<NewAppraisalRequest, ShopAppraisalResponse>;
    /**
     * retrieves info about the character associated with the given token + app
     *
     * @generated from protobuf rpc: TokenInfo(etco_proto.TokenInfoRequest) returns (etco_proto.TokenInfoResponse);
     */
    tokenInfo(input: TokenInfoRequest, options?: RpcOptions): UnaryCall<TokenInfoRequest, TokenInfoResponse>;
    // // (Admin)

    /**
     * retrieves the contract queue (appraisal codes with an extant contract)
     *
     * @generated from protobuf rpc: BuybackContractQueue(etco_proto.BasicRequest) returns (etco_proto.BuybackContractQueueResponse);
     */
    buybackContractQueue(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, BuybackContractQueueResponse>;
    /**
     * @generated from protobuf rpc: ShopContractQueue(etco_proto.BasicRequest) returns (etco_proto.ShopContractQueueResponse);
     */
    shopContractQueue(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, ShopContractQueueResponse>;
    /**
     * retrieves the purchase queue (appraisal codes in the purchase queue with no contract)
     *
     * @generated from protobuf rpc: PurchaseQueue(etco_proto.BasicRequest) returns (etco_proto.PurchaseQueueResponse);
     */
    purchaseQueue(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, PurchaseQueueResponse>;
    /**
     * retrieves the purchase queue for the specified location
     *
     * @generated from protobuf rpc: LocationPurchaseQueue(etco_proto.LocationPurchaseQueueRequest) returns (etco_proto.LocationPurchaseQueueResponse);
     */
    locationPurchaseQueue(input: LocationPurchaseQueueRequest, options?: RpcOptions): UnaryCall<LocationPurchaseQueueRequest, LocationPurchaseQueueResponse>;
    /**
     * deletes the specified codes from the purchase queue
     *
     * @generated from protobuf rpc: DeletePurchases(etco_proto.DeletePurchasesRequest) returns (etco_proto.DeletePurchasesResponse);
     */
    deletePurchases(input: DeletePurchasesRequest, options?: RpcOptions): UnaryCall<DeletePurchasesRequest, DeletePurchasesResponse>;
    // // (User+Creator)

    /**
     * cancels an existing purchase order
     * admin should use DeletePurchases instead
     *
     * @generated from protobuf rpc: CancelPurchase(etco_proto.CancelPurchaseRequest) returns (etco_proto.CancelPurchaseResponse);
     */
    cancelPurchase(input: CancelPurchaseRequest, options?: RpcOptions): UnaryCall<CancelPurchaseRequest, CancelPurchaseResponse>;
    // // (User+SameCharacter) or (Admin)

    /**
     * retrieves the appraisal codes for the given character
     *
     * @generated from protobuf rpc: UserBuybackAppraisalCodes(etco_proto.UserDataRequest) returns (etco_proto.UserAppraisalCodesResponse);
     */
    userBuybackAppraisalCodes(input: UserDataRequest, options?: RpcOptions): UnaryCall<UserDataRequest, UserAppraisalCodesResponse>;
    /**
     * @generated from protobuf rpc: UserShopAppraisalCodes(etco_proto.UserDataRequest) returns (etco_proto.UserAppraisalCodesResponse);
     */
    userShopAppraisalCodes(input: UserDataRequest, options?: RpcOptions): UnaryCall<UserDataRequest, UserAppraisalCodesResponse>;
    /**
     * retrieves the time of the last action for the given character
     *
     * @generated from protobuf rpc: UserMadePurchase(etco_proto.UserDataRequest) returns (etco_proto.UserTimePurchaseResponse);
     */
    userMadePurchase(input: UserDataRequest, options?: RpcOptions): UnaryCall<UserDataRequest, UserTimePurchaseResponse>;
    /**
     * @generated from protobuf rpc: UserCancelledPurchase(etco_proto.UserDataRequest) returns (etco_proto.UserTimePurchaseResponse);
     */
    userCancelledPurchase(input: UserDataRequest, options?: RpcOptions): UnaryCall<UserDataRequest, UserTimePurchaseResponse>;
    // // (User) or (Admin)

    /**
     * retrieves the available purchasable items for the given location
     *
     * @generated from protobuf rpc: ShopInventory(etco_proto.ShopInventoryRequest) returns (etco_proto.ShopInventoryResponse);
     */
    shopInventory(input: ShopInventoryRequest, options?: RpcOptions): UnaryCall<ShopInventoryRequest, ShopInventoryResponse>;
    /**
     * creates a new appraisal that is saved and will be retrievable later
     *
     * @generated from protobuf rpc: SaveBuybackAppraisal(etco_proto.SaveAppraisalRequest) returns (etco_proto.BuybackAppraisalResponse);
     */
    saveBuybackAppraisal(input: SaveAppraisalRequest, options?: RpcOptions): UnaryCall<SaveAppraisalRequest, BuybackAppraisalResponse>;
    /**
     * @generated from protobuf rpc: SaveShopAppraisal(etco_proto.SaveAppraisalRequest) returns (etco_proto.ShopAppraisalResponse);
     */
    saveShopAppraisal(input: SaveAppraisalRequest, options?: RpcOptions): UnaryCall<SaveAppraisalRequest, ShopAppraisalResponse>;
    // // (Creator) or (Admin)

    /**
     * retrieves the current status of the appraisal
     *
     * @generated from protobuf rpc: StatusBuybackAppraisal(etco_proto.StatusAppraisalRequest) returns (etco_proto.StatusAppraisalResponse);
     */
    statusBuybackAppraisal(input: StatusAppraisalRequest, options?: RpcOptions): UnaryCall<StatusAppraisalRequest, StatusAppraisalResponse>;
    /**
     * @generated from protobuf rpc: StatusShopAppraisal(etco_proto.StatusAppraisalRequest) returns (etco_proto.StatusAppraisalResponse);
     */
    statusShopAppraisal(input: StatusAppraisalRequest, options?: RpcOptions): UnaryCall<StatusAppraisalRequest, StatusAppraisalResponse>;
    // // (Anonymous) or (Creator) or (Admin)
    // // If (Creator) or (Admin), returns character_id

    /**
     * retrieves the appraisal for the given code
     *
     * @generated from protobuf rpc: GetBuybackAppraisal(etco_proto.GetAppraisalRequest) returns (etco_proto.GetBuybackAppraisalResponse);
     */
    getBuybackAppraisal(input: GetAppraisalRequest, options?: RpcOptions): UnaryCall<GetAppraisalRequest, GetBuybackAppraisalResponse>;
    /**
     * @generated from protobuf rpc: GetShopAppraisal(etco_proto.GetAppraisalRequest) returns (etco_proto.GetShopAppraisalResponse);
     */
    getShopAppraisal(input: GetAppraisalRequest, options?: RpcOptions): UnaryCall<GetAppraisalRequest, GetShopAppraisalResponse>;
    // // (Cfg) (Admin)

    /**
     * Get the requested config data
     *
     * @generated from protobuf rpc: CfgGetUserAuthList(etco_proto.BasicRequest) returns (etco_proto.CfgGetAuthListResponse);
     */
    cfgGetUserAuthList(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetAuthListResponse>;
    /**
     * @generated from protobuf rpc: CfgGetAdminAuthList(etco_proto.BasicRequest) returns (etco_proto.CfgGetAuthListResponse);
     */
    cfgGetAdminAuthList(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetAuthListResponse>;
    /**
     * @generated from protobuf rpc: CfgGetBuybackSystemTypeMapsBuilder(etco_proto.BasicRequest) returns (etco_proto.CfgGetBuybackSystemTypeMapsBuilderResponse);
     */
    cfgGetBuybackSystemTypeMapsBuilder(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetBuybackSystemTypeMapsBuilderResponse>;
    /**
     * @generated from protobuf rpc: CfgGetShopLocationTypeMapsBuilder(etco_proto.BasicRequest) returns (etco_proto.CfgGetShopLocationTypeMapsBuilderResponse);
     */
    cfgGetShopLocationTypeMapsBuilder(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetShopLocationTypeMapsBuilderResponse>;
    /**
     * @generated from protobuf rpc: CfgGetBuybackSystems(etco_proto.BasicRequest) returns (etco_proto.CfgGetBuybackSystemsResponse);
     */
    cfgGetBuybackSystems(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetBuybackSystemsResponse>;
    /**
     * @generated from protobuf rpc: CfgGetShopLocations(etco_proto.BasicRequest) returns (etco_proto.CfgGetShopLocationsResponse);
     */
    cfgGetShopLocations(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetShopLocationsResponse>;
    /**
     * @generated from protobuf rpc: CfgGetMarkets(etco_proto.BasicRequest) returns (etco_proto.CfgGetMarketsResponse);
     */
    cfgGetMarkets(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetMarketsResponse>;
    /**
     * @generated from protobuf rpc: CfgGetMarketNames(etco_proto.BasicRequest) returns (etco_proto.CfgGetMarketNamesResponse);
     */
    cfgGetMarketNames(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetMarketNamesResponse>;
    /**
     * @generated from protobuf rpc: CfgGetBuybackBundleKeys(etco_proto.BasicRequest) returns (etco_proto.CfgGetBuybackBundleKeysResponse);
     */
    cfgGetBuybackBundleKeys(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetBuybackBundleKeysResponse>;
    /**
     * @generated from protobuf rpc: CfgGetShopBundleKeys(etco_proto.BasicRequest) returns (etco_proto.CfgGetShopBundleKeysResponse);
     */
    cfgGetShopBundleKeys(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetShopBundleKeysResponse>;
    /**
     * @generated from protobuf rpc: CfgGetConstData(etco_proto.BasicRequest) returns (etco_proto.CfgGetConstDataResponse);
     */
    cfgGetConstData(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetConstDataResponse>;
    /**
     * Replace existing config data with the given config data
     *
     * @generated from protobuf rpc: CfgSetUserAuthList(etco_proto.CfgSetAuthListRequest) returns (etco_proto.CfgUpdateResponse);
     */
    cfgSetUserAuthList(input: CfgSetAuthListRequest, options?: RpcOptions): UnaryCall<CfgSetAuthListRequest, CfgUpdateResponse>;
    /**
     * @generated from protobuf rpc: CfgSetAdminAuthList(etco_proto.CfgSetAuthListRequest) returns (etco_proto.CfgUpdateResponse);
     */
    cfgSetAdminAuthList(input: CfgSetAuthListRequest, options?: RpcOptions): UnaryCall<CfgSetAuthListRequest, CfgUpdateResponse>;
    /**
     * @generated from protobuf rpc: CfgSetConstData(etco_proto.CfgSetConstDataRequest) returns (etco_proto.CfgUpdateResponse);
     */
    cfgSetConstData(input: CfgSetConstDataRequest, options?: RpcOptions): UnaryCall<CfgSetConstDataRequest, CfgUpdateResponse>;
    /**
     * Merge the given config data into the existing config data
     *
     * @generated from protobuf rpc: CfgMergeBuybackSystemTypeMapsBuilder(etco_proto.CfgMergeBuybackSystemTypeMapsBuilderRequest) returns (etco_proto.CfgUpdateResponse);
     */
    cfgMergeBuybackSystemTypeMapsBuilder(input: CfgMergeBuybackSystemTypeMapsBuilderRequest, options?: RpcOptions): UnaryCall<CfgMergeBuybackSystemTypeMapsBuilderRequest, CfgUpdateResponse>;
    /**
     * @generated from protobuf rpc: CfgMergeShopLocationTypeMapsBuilder(etco_proto.CfgMergeShopLocationTypeMapsBuilderRequest) returns (etco_proto.CfgUpdateResponse);
     */
    cfgMergeShopLocationTypeMapsBuilder(input: CfgMergeShopLocationTypeMapsBuilderRequest, options?: RpcOptions): UnaryCall<CfgMergeShopLocationTypeMapsBuilderRequest, CfgUpdateResponse>;
    /**
     * @generated from protobuf rpc: CfgMergeBuybackSystems(etco_proto.CfgMergeBuybackSystemsRequest) returns (etco_proto.CfgUpdateResponse);
     */
    cfgMergeBuybackSystems(input: CfgMergeBuybackSystemsRequest, options?: RpcOptions): UnaryCall<CfgMergeBuybackSystemsRequest, CfgUpdateResponse>;
    /**
     * @generated from protobuf rpc: CfgMergeShopLocations(etco_proto.CfgMergeShopLocationsRequest) returns (etco_proto.CfgUpdateResponse);
     */
    cfgMergeShopLocations(input: CfgMergeShopLocationsRequest, options?: RpcOptions): UnaryCall<CfgMergeShopLocationsRequest, CfgUpdateResponse>;
    /**
     * @generated from protobuf rpc: CfgMergeMarkets(etco_proto.CfgMergeMarketsRequest) returns (etco_proto.CfgUpdateResponse);
     */
    cfgMergeMarkets(input: CfgMergeMarketsRequest, options?: RpcOptions): UnaryCall<CfgMergeMarketsRequest, CfgUpdateResponse>;
}
/**
 * // (Anonymous) (Static)
 *
 * @generated from protobuf service etco_proto.EveTradingCo
 */
export class EveTradingCoClient implements IEveTradingCoClient, ServiceInfo {
    typeName = EveTradingCo.typeName;
    methods = EveTradingCo.methods;
    options = EveTradingCo.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * every published type with a market group
     *
     * @generated from protobuf rpc: AllTypes(etco_proto.EmptyRequest) returns (etco_proto.TypesResponse);
     */
    allTypes(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, TypesResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<EmptyRequest, TypesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AllNamedTypes(etco_proto.EmptyRequest) returns (etco_proto.NamedTypesResponse);
     */
    allNamedTypes(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, NamedTypesResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<EmptyRequest, NamedTypesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * requested published types with a market group
     *
     * @generated from protobuf rpc: NamedTypes(etco_proto.NamedTypesRequest) returns (etco_proto.NamedTypesResponse);
     */
    namedTypes(input: NamedTypesRequest, options?: RpcOptions): UnaryCall<NamedTypesRequest, NamedTypesResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<NamedTypesRequest, NamedTypesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * every available buyback system
     *
     * @generated from protobuf rpc: AllBuybackSystems(etco_proto.EmptyRequest) returns (etco_proto.SystemsResponse);
     */
    allBuybackSystems(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, SystemsResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<EmptyRequest, SystemsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * every system
     *
     * @generated from protobuf rpc: AllSystems(etco_proto.EmptyRequest) returns (etco_proto.SystemsResponse);
     */
    allSystems(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, SystemsResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<EmptyRequest, SystemsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * requested systems
     *
     * @generated from protobuf rpc: Systems(etco_proto.SystemsRequest) returns (etco_proto.SystemsResponse);
     */
    systems(input: SystemsRequest, options?: RpcOptions): UnaryCall<SystemsRequest, SystemsResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<SystemsRequest, SystemsResponse>("unary", this._transport, method, opt, input);
    }
    // // (Anonymous)

    /**
     * every available shop location
     *
     * @generated from protobuf rpc: AllShopLocations(etco_proto.EmptyRequest) returns (etco_proto.AllShopLocationsResponse);
     */
    allShopLocations(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, AllShopLocationsResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<EmptyRequest, AllShopLocationsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * requested locations
     *
     * @generated from protobuf rpc: Locations(etco_proto.LocationsRequest) returns (etco_proto.LocationsResponse);
     */
    locations(input: LocationsRequest, options?: RpcOptions): UnaryCall<LocationsRequest, LocationsResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<LocationsRequest, LocationsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * logs into the requested app (users will only ever use the Auth app)
     *
     * @generated from protobuf rpc: Login(etco_proto.LoginRequest) returns (etco_proto.LoginResponse);
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginRequest, LoginResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * parses an input string into a list of named basic items
     *
     * @generated from protobuf rpc: Parse(etco_proto.ParseRequest) returns (etco_proto.ParseResponse);
     */
    parse(input: ParseRequest, options?: RpcOptions): UnaryCall<ParseRequest, ParseResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<ParseRequest, ParseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * retrieves information about the given entity
     *
     * @generated from protobuf rpc: CharacterInfo(etco_proto.EntityInfoRequest) returns (etco_proto.CharacterInfoResponse);
     */
    characterInfo(input: EntityInfoRequest, options?: RpcOptions): UnaryCall<EntityInfoRequest, CharacterInfoResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<EntityInfoRequest, CharacterInfoResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CorporationInfo(etco_proto.EntityInfoRequest) returns (etco_proto.CorporationInfoResponse);
     */
    corporationInfo(input: EntityInfoRequest, options?: RpcOptions): UnaryCall<EntityInfoRequest, CorporationInfoResponse> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<EntityInfoRequest, CorporationInfoResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AllianceInfo(etco_proto.EntityInfoRequest) returns (etco_proto.AllianceInfoResponse);
     */
    allianceInfo(input: EntityInfoRequest, options?: RpcOptions): UnaryCall<EntityInfoRequest, AllianceInfoResponse> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<EntityInfoRequest, AllianceInfoResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * creates a new appraisal that is not saved and will not be retrievable later
     *
     * @generated from protobuf rpc: NewBuybackAppraisal(etco_proto.NewAppraisalRequest) returns (etco_proto.BuybackAppraisalResponse);
     */
    newBuybackAppraisal(input: NewAppraisalRequest, options?: RpcOptions): UnaryCall<NewAppraisalRequest, BuybackAppraisalResponse> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<NewAppraisalRequest, BuybackAppraisalResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: NewShopAppraisal(etco_proto.NewAppraisalRequest) returns (etco_proto.ShopAppraisalResponse);
     */
    newShopAppraisal(input: NewAppraisalRequest, options?: RpcOptions): UnaryCall<NewAppraisalRequest, ShopAppraisalResponse> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<NewAppraisalRequest, ShopAppraisalResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * retrieves info about the character associated with the given token + app
     *
     * @generated from protobuf rpc: TokenInfo(etco_proto.TokenInfoRequest) returns (etco_proto.TokenInfoResponse);
     */
    tokenInfo(input: TokenInfoRequest, options?: RpcOptions): UnaryCall<TokenInfoRequest, TokenInfoResponse> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<TokenInfoRequest, TokenInfoResponse>("unary", this._transport, method, opt, input);
    }
    // // (Admin)

    /**
     * retrieves the contract queue (appraisal codes with an extant contract)
     *
     * @generated from protobuf rpc: BuybackContractQueue(etco_proto.BasicRequest) returns (etco_proto.BuybackContractQueueResponse);
     */
    buybackContractQueue(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, BuybackContractQueueResponse> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<BasicRequest, BuybackContractQueueResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ShopContractQueue(etco_proto.BasicRequest) returns (etco_proto.ShopContractQueueResponse);
     */
    shopContractQueue(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, ShopContractQueueResponse> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<BasicRequest, ShopContractQueueResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * retrieves the purchase queue (appraisal codes in the purchase queue with no contract)
     *
     * @generated from protobuf rpc: PurchaseQueue(etco_proto.BasicRequest) returns (etco_proto.PurchaseQueueResponse);
     */
    purchaseQueue(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, PurchaseQueueResponse> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<BasicRequest, PurchaseQueueResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * retrieves the purchase queue for the specified location
     *
     * @generated from protobuf rpc: LocationPurchaseQueue(etco_proto.LocationPurchaseQueueRequest) returns (etco_proto.LocationPurchaseQueueResponse);
     */
    locationPurchaseQueue(input: LocationPurchaseQueueRequest, options?: RpcOptions): UnaryCall<LocationPurchaseQueueRequest, LocationPurchaseQueueResponse> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<LocationPurchaseQueueRequest, LocationPurchaseQueueResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * deletes the specified codes from the purchase queue
     *
     * @generated from protobuf rpc: DeletePurchases(etco_proto.DeletePurchasesRequest) returns (etco_proto.DeletePurchasesResponse);
     */
    deletePurchases(input: DeletePurchasesRequest, options?: RpcOptions): UnaryCall<DeletePurchasesRequest, DeletePurchasesResponse> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePurchasesRequest, DeletePurchasesResponse>("unary", this._transport, method, opt, input);
    }
    // // (User+Creator)

    /**
     * cancels an existing purchase order
     * admin should use DeletePurchases instead
     *
     * @generated from protobuf rpc: CancelPurchase(etco_proto.CancelPurchaseRequest) returns (etco_proto.CancelPurchaseResponse);
     */
    cancelPurchase(input: CancelPurchaseRequest, options?: RpcOptions): UnaryCall<CancelPurchaseRequest, CancelPurchaseResponse> {
        const method = this.methods[21], opt = this._transport.mergeOptions(options);
        return stackIntercept<CancelPurchaseRequest, CancelPurchaseResponse>("unary", this._transport, method, opt, input);
    }
    // // (User+SameCharacter) or (Admin)

    /**
     * retrieves the appraisal codes for the given character
     *
     * @generated from protobuf rpc: UserBuybackAppraisalCodes(etco_proto.UserDataRequest) returns (etco_proto.UserAppraisalCodesResponse);
     */
    userBuybackAppraisalCodes(input: UserDataRequest, options?: RpcOptions): UnaryCall<UserDataRequest, UserAppraisalCodesResponse> {
        const method = this.methods[22], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserDataRequest, UserAppraisalCodesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UserShopAppraisalCodes(etco_proto.UserDataRequest) returns (etco_proto.UserAppraisalCodesResponse);
     */
    userShopAppraisalCodes(input: UserDataRequest, options?: RpcOptions): UnaryCall<UserDataRequest, UserAppraisalCodesResponse> {
        const method = this.methods[23], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserDataRequest, UserAppraisalCodesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * retrieves the time of the last action for the given character
     *
     * @generated from protobuf rpc: UserMadePurchase(etco_proto.UserDataRequest) returns (etco_proto.UserTimePurchaseResponse);
     */
    userMadePurchase(input: UserDataRequest, options?: RpcOptions): UnaryCall<UserDataRequest, UserTimePurchaseResponse> {
        const method = this.methods[24], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserDataRequest, UserTimePurchaseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UserCancelledPurchase(etco_proto.UserDataRequest) returns (etco_proto.UserTimePurchaseResponse);
     */
    userCancelledPurchase(input: UserDataRequest, options?: RpcOptions): UnaryCall<UserDataRequest, UserTimePurchaseResponse> {
        const method = this.methods[25], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserDataRequest, UserTimePurchaseResponse>("unary", this._transport, method, opt, input);
    }
    // // (User) or (Admin)

    /**
     * retrieves the available purchasable items for the given location
     *
     * @generated from protobuf rpc: ShopInventory(etco_proto.ShopInventoryRequest) returns (etco_proto.ShopInventoryResponse);
     */
    shopInventory(input: ShopInventoryRequest, options?: RpcOptions): UnaryCall<ShopInventoryRequest, ShopInventoryResponse> {
        const method = this.methods[26], opt = this._transport.mergeOptions(options);
        return stackIntercept<ShopInventoryRequest, ShopInventoryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * creates a new appraisal that is saved and will be retrievable later
     *
     * @generated from protobuf rpc: SaveBuybackAppraisal(etco_proto.SaveAppraisalRequest) returns (etco_proto.BuybackAppraisalResponse);
     */
    saveBuybackAppraisal(input: SaveAppraisalRequest, options?: RpcOptions): UnaryCall<SaveAppraisalRequest, BuybackAppraisalResponse> {
        const method = this.methods[27], opt = this._transport.mergeOptions(options);
        return stackIntercept<SaveAppraisalRequest, BuybackAppraisalResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SaveShopAppraisal(etco_proto.SaveAppraisalRequest) returns (etco_proto.ShopAppraisalResponse);
     */
    saveShopAppraisal(input: SaveAppraisalRequest, options?: RpcOptions): UnaryCall<SaveAppraisalRequest, ShopAppraisalResponse> {
        const method = this.methods[28], opt = this._transport.mergeOptions(options);
        return stackIntercept<SaveAppraisalRequest, ShopAppraisalResponse>("unary", this._transport, method, opt, input);
    }
    // // (Creator) or (Admin)

    /**
     * retrieves the current status of the appraisal
     *
     * @generated from protobuf rpc: StatusBuybackAppraisal(etco_proto.StatusAppraisalRequest) returns (etco_proto.StatusAppraisalResponse);
     */
    statusBuybackAppraisal(input: StatusAppraisalRequest, options?: RpcOptions): UnaryCall<StatusAppraisalRequest, StatusAppraisalResponse> {
        const method = this.methods[29], opt = this._transport.mergeOptions(options);
        return stackIntercept<StatusAppraisalRequest, StatusAppraisalResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: StatusShopAppraisal(etco_proto.StatusAppraisalRequest) returns (etco_proto.StatusAppraisalResponse);
     */
    statusShopAppraisal(input: StatusAppraisalRequest, options?: RpcOptions): UnaryCall<StatusAppraisalRequest, StatusAppraisalResponse> {
        const method = this.methods[30], opt = this._transport.mergeOptions(options);
        return stackIntercept<StatusAppraisalRequest, StatusAppraisalResponse>("unary", this._transport, method, opt, input);
    }
    // // (Anonymous) or (Creator) or (Admin)
    // // If (Creator) or (Admin), returns character_id

    /**
     * retrieves the appraisal for the given code
     *
     * @generated from protobuf rpc: GetBuybackAppraisal(etco_proto.GetAppraisalRequest) returns (etco_proto.GetBuybackAppraisalResponse);
     */
    getBuybackAppraisal(input: GetAppraisalRequest, options?: RpcOptions): UnaryCall<GetAppraisalRequest, GetBuybackAppraisalResponse> {
        const method = this.methods[31], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAppraisalRequest, GetBuybackAppraisalResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetShopAppraisal(etco_proto.GetAppraisalRequest) returns (etco_proto.GetShopAppraisalResponse);
     */
    getShopAppraisal(input: GetAppraisalRequest, options?: RpcOptions): UnaryCall<GetAppraisalRequest, GetShopAppraisalResponse> {
        const method = this.methods[32], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAppraisalRequest, GetShopAppraisalResponse>("unary", this._transport, method, opt, input);
    }
    // // (Cfg) (Admin)

    /**
     * Get the requested config data
     *
     * @generated from protobuf rpc: CfgGetUserAuthList(etco_proto.BasicRequest) returns (etco_proto.CfgGetAuthListResponse);
     */
    cfgGetUserAuthList(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetAuthListResponse> {
        const method = this.methods[33], opt = this._transport.mergeOptions(options);
        return stackIntercept<BasicRequest, CfgGetAuthListResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgGetAdminAuthList(etco_proto.BasicRequest) returns (etco_proto.CfgGetAuthListResponse);
     */
    cfgGetAdminAuthList(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetAuthListResponse> {
        const method = this.methods[34], opt = this._transport.mergeOptions(options);
        return stackIntercept<BasicRequest, CfgGetAuthListResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgGetBuybackSystemTypeMapsBuilder(etco_proto.BasicRequest) returns (etco_proto.CfgGetBuybackSystemTypeMapsBuilderResponse);
     */
    cfgGetBuybackSystemTypeMapsBuilder(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetBuybackSystemTypeMapsBuilderResponse> {
        const method = this.methods[35], opt = this._transport.mergeOptions(options);
        return stackIntercept<BasicRequest, CfgGetBuybackSystemTypeMapsBuilderResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgGetShopLocationTypeMapsBuilder(etco_proto.BasicRequest) returns (etco_proto.CfgGetShopLocationTypeMapsBuilderResponse);
     */
    cfgGetShopLocationTypeMapsBuilder(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetShopLocationTypeMapsBuilderResponse> {
        const method = this.methods[36], opt = this._transport.mergeOptions(options);
        return stackIntercept<BasicRequest, CfgGetShopLocationTypeMapsBuilderResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgGetBuybackSystems(etco_proto.BasicRequest) returns (etco_proto.CfgGetBuybackSystemsResponse);
     */
    cfgGetBuybackSystems(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetBuybackSystemsResponse> {
        const method = this.methods[37], opt = this._transport.mergeOptions(options);
        return stackIntercept<BasicRequest, CfgGetBuybackSystemsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgGetShopLocations(etco_proto.BasicRequest) returns (etco_proto.CfgGetShopLocationsResponse);
     */
    cfgGetShopLocations(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetShopLocationsResponse> {
        const method = this.methods[38], opt = this._transport.mergeOptions(options);
        return stackIntercept<BasicRequest, CfgGetShopLocationsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgGetMarkets(etco_proto.BasicRequest) returns (etco_proto.CfgGetMarketsResponse);
     */
    cfgGetMarkets(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetMarketsResponse> {
        const method = this.methods[39], opt = this._transport.mergeOptions(options);
        return stackIntercept<BasicRequest, CfgGetMarketsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgGetMarketNames(etco_proto.BasicRequest) returns (etco_proto.CfgGetMarketNamesResponse);
     */
    cfgGetMarketNames(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetMarketNamesResponse> {
        const method = this.methods[40], opt = this._transport.mergeOptions(options);
        return stackIntercept<BasicRequest, CfgGetMarketNamesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgGetBuybackBundleKeys(etco_proto.BasicRequest) returns (etco_proto.CfgGetBuybackBundleKeysResponse);
     */
    cfgGetBuybackBundleKeys(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetBuybackBundleKeysResponse> {
        const method = this.methods[41], opt = this._transport.mergeOptions(options);
        return stackIntercept<BasicRequest, CfgGetBuybackBundleKeysResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgGetShopBundleKeys(etco_proto.BasicRequest) returns (etco_proto.CfgGetShopBundleKeysResponse);
     */
    cfgGetShopBundleKeys(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetShopBundleKeysResponse> {
        const method = this.methods[42], opt = this._transport.mergeOptions(options);
        return stackIntercept<BasicRequest, CfgGetShopBundleKeysResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgGetConstData(etco_proto.BasicRequest) returns (etco_proto.CfgGetConstDataResponse);
     */
    cfgGetConstData(input: BasicRequest, options?: RpcOptions): UnaryCall<BasicRequest, CfgGetConstDataResponse> {
        const method = this.methods[43], opt = this._transport.mergeOptions(options);
        return stackIntercept<BasicRequest, CfgGetConstDataResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Replace existing config data with the given config data
     *
     * @generated from protobuf rpc: CfgSetUserAuthList(etco_proto.CfgSetAuthListRequest) returns (etco_proto.CfgUpdateResponse);
     */
    cfgSetUserAuthList(input: CfgSetAuthListRequest, options?: RpcOptions): UnaryCall<CfgSetAuthListRequest, CfgUpdateResponse> {
        const method = this.methods[44], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgSetAuthListRequest, CfgUpdateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgSetAdminAuthList(etco_proto.CfgSetAuthListRequest) returns (etco_proto.CfgUpdateResponse);
     */
    cfgSetAdminAuthList(input: CfgSetAuthListRequest, options?: RpcOptions): UnaryCall<CfgSetAuthListRequest, CfgUpdateResponse> {
        const method = this.methods[45], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgSetAuthListRequest, CfgUpdateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgSetConstData(etco_proto.CfgSetConstDataRequest) returns (etco_proto.CfgUpdateResponse);
     */
    cfgSetConstData(input: CfgSetConstDataRequest, options?: RpcOptions): UnaryCall<CfgSetConstDataRequest, CfgUpdateResponse> {
        const method = this.methods[46], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgSetConstDataRequest, CfgUpdateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Merge the given config data into the existing config data
     *
     * @generated from protobuf rpc: CfgMergeBuybackSystemTypeMapsBuilder(etco_proto.CfgMergeBuybackSystemTypeMapsBuilderRequest) returns (etco_proto.CfgUpdateResponse);
     */
    cfgMergeBuybackSystemTypeMapsBuilder(input: CfgMergeBuybackSystemTypeMapsBuilderRequest, options?: RpcOptions): UnaryCall<CfgMergeBuybackSystemTypeMapsBuilderRequest, CfgUpdateResponse> {
        const method = this.methods[47], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgMergeBuybackSystemTypeMapsBuilderRequest, CfgUpdateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgMergeShopLocationTypeMapsBuilder(etco_proto.CfgMergeShopLocationTypeMapsBuilderRequest) returns (etco_proto.CfgUpdateResponse);
     */
    cfgMergeShopLocationTypeMapsBuilder(input: CfgMergeShopLocationTypeMapsBuilderRequest, options?: RpcOptions): UnaryCall<CfgMergeShopLocationTypeMapsBuilderRequest, CfgUpdateResponse> {
        const method = this.methods[48], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgMergeShopLocationTypeMapsBuilderRequest, CfgUpdateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgMergeBuybackSystems(etco_proto.CfgMergeBuybackSystemsRequest) returns (etco_proto.CfgUpdateResponse);
     */
    cfgMergeBuybackSystems(input: CfgMergeBuybackSystemsRequest, options?: RpcOptions): UnaryCall<CfgMergeBuybackSystemsRequest, CfgUpdateResponse> {
        const method = this.methods[49], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgMergeBuybackSystemsRequest, CfgUpdateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgMergeShopLocations(etco_proto.CfgMergeShopLocationsRequest) returns (etco_proto.CfgUpdateResponse);
     */
    cfgMergeShopLocations(input: CfgMergeShopLocationsRequest, options?: RpcOptions): UnaryCall<CfgMergeShopLocationsRequest, CfgUpdateResponse> {
        const method = this.methods[50], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgMergeShopLocationsRequest, CfgUpdateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CfgMergeMarkets(etco_proto.CfgMergeMarketsRequest) returns (etco_proto.CfgUpdateResponse);
     */
    cfgMergeMarkets(input: CfgMergeMarketsRequest, options?: RpcOptions): UnaryCall<CfgMergeMarketsRequest, CfgUpdateResponse> {
        const method = this.methods[51], opt = this._transport.mergeOptions(options);
        return stackIntercept<CfgMergeMarketsRequest, CfgUpdateResponse>("unary", this._transport, method, opt, input);
    }
}
